[package]
name = "any-store"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.113"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
strip = true
debug = false
## panic = "abort"
opt-level = 3
lto = true
codegen-units = 1  
