[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals,+simd128",
  "-C", "link-arg=--shared-memory",
  "-C", "link-arg=--max-memory=1073741824",
  "-C", "link-arg=--import-memory"
]

[unstable]
build-std = ["std", "panic_abort"]

[alias]
wasm = "build --release --target=wasm32-unknown-unknown"