[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals,+simd128",
  "-C", "link-arg=--shared-memory",
  "-C", "link-arg=--import-memory",
  "-C", "link-args=--export=__wasm_init_tls",
  "-C", "link-args=--export=__tls_size",
  "-C", "link-args=--export=__tls_align",
  "-C", "link-args=--export=__tls_base",
  "-C", "link-arg=--max-memory=1073741824",
]

[unstable]
build-std = ["std", "panic_abort"]

[alias]
wasm = "build --release --target=wasm32-unknown-unknown"